import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { listen } from "@tauri-apps/api/event";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { languageLabel } from "@/lib/languages";
import { selectProvider } from "@/lib/providers";
import {
  countRosettaPdfPages,
  generateRosettaTranslatedPdf,
  getRosettaPdfAssets,
} from "@/lib/rosettaJobs";
import { isManagedRuntimeReady } from "@/lib/useManagedRwkvRuntime";
import {
  isPdf2zhReady,
  useManagedPdf2zhRuntime,
} from "@/lib/useManagedPdf2zhRuntime";
import { useRosettaStore } from "@/store/useRosettaStore";
import type {
  RosettaDocument,
  RosettaTranslationFile,
} from "../../types/rosetta";

import { PdfPane } from "./PdfPane";

type PreviewSide = "source" | "translation";

type Pdf2zhProgress = {
  jobId: string;
  phase: "parse" | "translate" | "render";
  percent: number | null;
  message: string;
};

type PdfDocumentPreviewProps = {
  jobId: string;
  document: RosettaDocument;
  translationFile: RosettaTranslationFile | null;
  /// Translation progress fields lifted from WorkspacePage so we can render a
  /// live "Translating… X / N" placeholder without subscribing the whole
  /// store here. Pass `completedSegments === segmentCount` to consider the
  /// translation finished.
  segmentCount: number;
  completedSegments: number;
  failedSegments: number;
  /// True while a translation run is actively writing back to segments.
  /// Without this we can't tell "translation started but slow" from "no one
  /// has clicked Translate yet" — both look like `completedSegments < total`.
  isTranslating: boolean;
};

/// Default rasterize width per pane. Backed by pdfium on the Rust side at
/// ~1.5x the source page width so retina screens stay crisp. The frontend
/// passes this to `renderRosettaPdfPageAsPng` per page; the backend clamps
/// to a safe range and derives the height from the source aspect ratio.
const DEFAULT_RASTER_WIDTH = 1200;

/// Side-by-side PDF preview. Both panes are rasterized server-side via
/// pdfium and shipped as PNG bytes per page. See [`PdfPane`] for the
/// rationale (pdfjs / `<embed>` both failed; pdfium-as-renderer mirrors
/// what macOS Preview shows).
export function PdfDocumentPreview({
  jobId,
  document,
  translationFile,
  segmentCount,
  completedSegments,
  failedSegments,
  isTranslating,
}: PdfDocumentPreviewProps) {
  const sourceScrollRef = useRef<HTMLDivElement | null>(null);
  const translationScrollRef = useRef<HTMLDivElement | null>(null);
  const scrollDriverRef = useRef<PreviewSide | null>(null);
  const scrollDriverTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const [sourcePageCount, setSourcePageCount] = useState<number | null>(null);
  const [translatedPageCount, setTranslatedPageCount] = useState<number | null>(null);
  const [paneWidth, setPaneWidth] = useState<number>(DEFAULT_RASTER_WIDTH);
  // Bumping forces PdfPane to re-fetch all pages — used after "重新生成" so
  // the user immediately sees the regenerated translated PDF.
  const [translatedCacheKey, setTranslatedCacheKey] = useState(0);
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [pdf2zhProgress, setPdf2zhProgress] = useState<Pdf2zhProgress | null>(null);
  const autoGeneratedForJobRef = useRef<string | null>(null);
  const paneContainerRef = useRef<HTMLDivElement | null>(null);
  const rwkv = useRosettaStore((state) => state.rwkv);
  const managedRuntimeStatus = useRosettaStore((state) => state.managedRuntime.status);
  const pdf2zhRuntime = useManagedPdf2zhRuntime();

  // Measure the pane container width so rasterization matches display. We
  // re-measure on resize so panel-resize/window-resize re-rasterize at the
  // right resolution. Devicepixel ratio is folded in so retina displays get
  // crisp pages without us asking pdfium for needless extra pixels.
  useLayoutEffect(() => {
    const el = paneContainerRef.current;
    if (!el) return;
    const measure = () => {
      const halfWidth = el.clientWidth / 2;
      const dpr = window.devicePixelRatio || 1;
      const want = Math.round(Math.max(400, halfWidth * dpr));
      setPaneWidth((prev) =>
        // Avoid resetting cache for tiny sub-pixel jitter that some resize
        // observers fire — only re-rasterize when the difference is real.
        Math.abs(prev - want) > 32 ? want : prev,
      );
    };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  // Probe both PDFs whenever the job changes: existence (via assets) +
  // page count (used to pre-allocate placeholders so the layout doesn't
  // jump as PNGs stream in).
  useEffect(() => {
    let cancelled = false;
    setSourcePageCount(null);
    setTranslatedPageCount(null);
    setGenerateError(null);
    autoGeneratedForJobRef.current = null;

    (async () => {
      try {
        const assets = await getRosettaPdfAssets(jobId);
        if (cancelled) return;
        const srcPages = await countRosettaPdfPages(jobId, "source");
        if (cancelled) return;
        setSourcePageCount(srcPages);
        if (assets.translatedPdf) {
          const tPages = await countRosettaPdfPages(jobId, "translated");
          if (cancelled) return;
          setTranslatedPageCount(tPages);
        } else {
          setTranslatedPageCount(0);
        }
      } catch (error) {
        if (cancelled) return;
        console.error("[pdf] failed to probe PDF page counts for job", jobId, error);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [jobId]);

  // Legacy segment-complete auto-generation remains for old Phase 2 jobs that
  // already have extracted PDF segments. New Phase 3 jobs generate directly
  // from the topbar's PDF-specific translate path.
  const translationComplete =
    segmentCount > 0 && completedSegments === segmentCount && failedSegments === 0;
  useEffect(() => {
    if (!translationComplete) return;
    if (translatedPageCount && translatedPageCount > 0) return;
    if (autoGeneratedForJobRef.current === jobId) return;
    autoGeneratedForJobRef.current = jobId;
    void runGenerate();
    // We intentionally do not depend on `runGenerate` itself — it doesn't
    // change identity but linting would suggest it; the autoGeneratedForJobRef
    // guard handles re-fires.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [translationComplete, translatedPageCount, jobId]);

  useEffect(() => {
    return () => {
      if (scrollDriverTimeoutRef.current) clearTimeout(scrollDriverTimeoutRef.current);
    };
  }, []);

  useEffect(() => {
    let unmounted = false;
    let unlisten: (() => void) | null = null;

    listen<Pdf2zhProgress>("rosetta-pdf2zh-progress", (event) => {
      if (event.payload.jobId !== jobId) return;
      setPdf2zhProgress(event.payload);
      setGenerating(event.payload.percent !== 100);
      if (event.payload.percent === 100) {
        void countRosettaPdfPages(jobId, "translated")
          .then((pages) => {
            setTranslatedPageCount(pages);
            setTranslatedCacheKey((key) => key + 1);
          })
          .catch(() => {});
      }
    })
      .then((fn) => {
        if (unmounted) {
          fn();
        } else {
          unlisten = fn;
        }
      })
      .catch(console.error);

    return () => {
      unmounted = true;
      unlisten?.();
    };
  }, [jobId]);

  useEffect(() => {
    if (translationFile?.status !== "translated") return;
    void countRosettaPdfPages(jobId, "translated")
      .then((pages) => {
        setTranslatedPageCount(pages);
        setTranslatedCacheKey((key) => key + 1);
      })
      .catch(() => {});
  }, [jobId, translationFile?.status, translationFile?.updatedAt]);

  async function runGenerate() {
    setGenerateError(null);
    setGenerating(true);
    try {
      await ensurePdf2zhReadyForGeneration();
      const provider = selectProvider({
        config: rwkv,
        managedRuntimeReady: isManagedRuntimeReady(managedRuntimeStatus),
        managedRuntimeBaseUrl: managedRuntimeStatus?.process.baseUrl ?? undefined,
      });
      await generateRosettaTranslatedPdf(jobId, {
        rwkvBaseUrl: provider.baseUrl,
        sourceLang: document.sourceLang ?? "en",
        targetLang: translationFile?.targetLang ?? document.targetLang,
        timeoutMs: rwkv.timeoutMs,
        ignoreCache: true,
      });
      const pages = await countRosettaPdfPages(jobId, "translated");
      setTranslatedPageCount(pages);
      // Bump cache key so PdfPane re-fetches PNGs for the new PDF bytes.
      setTranslatedCacheKey((k) => k + 1);
    } catch (error) {
      console.error("[pdf] generate_rosetta_translated_pdf failed", error);
      setGenerateError(
        error instanceof Error ? error.message : String(error ?? "翻译后 PDF 生成失败"),
      );
    } finally {
      setGenerating(false);
    }
  }

  async function ensurePdf2zhReadyForGeneration() {
    const current = await pdf2zhRuntime.refreshStatus();
    if (isPdf2zhReady(current)) return;
    if (current?.state === "unsupported") {
      throw new Error(current.message);
    }
    await pdf2zhRuntime.install({ repair: false });
    const refreshed = await pdf2zhRuntime.refreshStatus();
    if (!isPdf2zhReady(refreshed)) {
      throw new Error(
        refreshed?.message ??
          "PDFMathTranslate 安装完成后仍未就绪，请检查 pdf2zh pack。"
      );
    }
  }

  function syncScroll(side: PreviewSide) {
    if (scrollDriverRef.current !== null && scrollDriverRef.current !== side) return;
    const from =
      side === "source" ? sourceScrollRef.current : translationScrollRef.current;
    const to =
      side === "source" ? translationScrollRef.current : sourceScrollRef.current;
    if (!from || !to) return;

    const maxFrom = from.scrollHeight - from.clientHeight;
    const maxTo = to.scrollHeight - to.clientHeight;
    const ratio = maxFrom > 0 ? from.scrollTop / maxFrom : 0;
    const targetScrollTop = ratio * Math.max(maxTo, 0);
    if (Math.abs(to.scrollTop - targetScrollTop) < 2) return;

    scrollDriverRef.current = side;
    if (scrollDriverTimeoutRef.current) clearTimeout(scrollDriverTimeoutRef.current);
    scrollDriverTimeoutRef.current = setTimeout(() => {
      scrollDriverRef.current = null;
    }, 150);
    to.scrollTop = targetScrollTop;
  }

  const extractionStatus = document.extractionStatus ?? "done";
  const pdfAlreadyTranslated = translationFile?.status === "translated";
  const pdf2zhProgressText = pdf2zhProgress
    ? `${phaseLabel(pdf2zhProgress.phase)}${
        pdf2zhProgress.percent == null ? "" : ` ${pdf2zhProgress.percent}%`
      }`
    : null;
  const translationPlaceholder = (() => {
    if (extractionStatus === "pending") return "PDF 正在解析，请稍候…";
    if (extractionStatus === "failed") return "PDF 解析失败，请重新导入。";
    if (pdf2zhProgressText && generating) return pdf2zhProgressText;
    if (generating) return "正在生成翻译后 PDF…";
    if (generateError) return `生成失败：${generateError}`;
    if (pdfAlreadyTranslated) return "正在加载译文 PDF…";
    if (segmentCount === 0) return "等待翻译。PDF 将由 PDFMathTranslate 保留版面并生成译文 PDF。";
    if (translationComplete) return "等待生成翻译后 PDF…";
    if (isTranslating) return `翻译中… (${completedSegments} / ${segmentCount})`;
    if (completedSegments === 0)
      return `等待翻译。共 ${segmentCount} 段，点击「翻译全部」开始。`;
    return `翻译部分完成 (${completedSegments} / ${segmentCount})，继续翻译以生成完整译文 PDF。`;
  })();

  return (
    <Card className="flex h-full min-h-0 flex-col gap-0 overflow-hidden py-0">
      <div className="grid grid-cols-2 border-b bg-muted/40 text-sm text-muted-foreground">
        <div className="border-r px-4 py-3">
          <span>原文 PDF</span>
          <span className="ml-2 text-xs">
            {document.filename}
          </span>
        </div>
        <div className="flex items-center justify-between gap-3 px-4 py-3">
          <div className="flex items-center gap-2">
            <span>译文 PDF</span>
            {translationFile ? (
              <Badge variant="outline">{languageLabel(translationFile.targetLang)}</Badge>
            ) : null}
          </div>
          {translationComplete || pdfAlreadyTranslated ? (
            <Button
              size="sm"
              variant="ghost"
              onClick={runGenerate}
              disabled={generating}
            >
              {generating ? "生成中…" : "重新生成"}
            </Button>
          ) : null}
        </div>
      </div>
      <div ref={paneContainerRef} className="grid min-h-0 flex-1 grid-cols-2">
        <div className="min-h-0 border-r">
          <PdfPane
            jobId={jobId}
            kind="source"
            pageCount={sourcePageCount}
            targetWidth={paneWidth}
            placeholder="加载源 PDF…"
            scrollRef={sourceScrollRef}
            onScroll={() => syncScroll("source")}
          />
        </div>
        <div className="min-h-0">
          <PdfPane
            jobId={jobId}
            kind="translated"
            cacheKey={translatedCacheKey}
            pageCount={translatedPageCount}
            targetWidth={paneWidth}
            placeholder={translationPlaceholder}
            scrollRef={translationScrollRef}
            onScroll={() => syncScroll("translation")}
          />
        </div>
      </div>
    </Card>
  );
}

function phaseLabel(phase: Pdf2zhProgress["phase"]) {
  switch (phase) {
    case "parse":
      return "正在分析版面...";
    case "translate":
      return "正在翻译...";
    case "render":
      return "正在生成 PDF...";
  }
}
